version: "3.9"

volumes:
  node_modules:

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: react_fastapi_frontend_container
    tty: true
    volumes:
      - .:/app
      # - node_modules:/app/frontend/node_modules
    ports:
      - 5173:5173
    command: yarn dev
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: react_fastapi_backend_container
    ports:
      - 8080:8080
    tty: true
    volumes:
      - .:/app
